/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.cristalia.reagentes.principal;

import br.com.cristalia.biblioteca.authentication.FrmSenhaAlterar;
import br.com.cristalia.biblioteca.authentication.FrmUsuarioVisualizar;
import br.com.cristalia.biblioteca.dao.LoginDAO;
import br.com.cristalia.biblioteca.dao.SegurancaDAO;
import br.com.cristalia.biblioteca.dao.UsuarioDAO;
import br.com.cristalia.biblioteca.model.Seguranca;
import br.com.cristalia.biblioteca.model.Usuario;
import br.com.cristalia.biblioteca.util.AcessoSistema;
import br.com.cristalia.biblioteca.util.Frames;
import br.com.cristalia.biblioteca.util.MouseEventButton;
import br.com.cristalia.reagentes.view.FrmDocumentos;
import br.com.cristalia.reagentes.view.FrmReagente;
import java.awt.AWTEvent;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import static jdk.vm.ci.common.InitTimer.timer;

/**
 *
 * @author rafael.lopes
 */
public class FrmPrincipal extends javax.swing.JFrame {

    //private Timer timer;
    private Long timer;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        pnlReagente.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmReagente.class.getSimpleName())));
        pnlDocumentos.setVisible(AcessoSistema.acessoDados(new AcessoSistema().getAcessoSistema(FrmDocumentos.class.getSimpleName())));
        carregar();
        checkTempoInatividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTopMenu = new javax.swing.JPanel();
        lblLabMenuTop = new javax.swing.JLabel();
        lblLogoMenuTop = new javax.swing.JLabel();
        lblLimsMenuTop = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlDocumentos = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlReagente = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(892, 40));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_exit_25.png"))); // NOI18N
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLogOutMouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_reset_password_25.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_user_25.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        pnlTopMenu.setBackground(new java.awt.Color(181, 220, 237));
        pnlTopMenu.setPreferredSize(new java.awt.Dimension(0, 40));
        pnlTopMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLabMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLabMenuTop.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblLabMenuTop.setForeground(new java.awt.Color(0, 102, 102));
        lblLabMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLabMenuTop.setText("Lab");
        pnlTopMenu.add(lblLabMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        lblLogoMenuTop.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoMenuTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_lablims_32.png"))); // NOI18N
        lblLogoMenuTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTopMenu.add(lblLogoMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 20, 40));

        lblLimsMenuTop.setBackground(new java.awt.Color(153, 153, 153));
        lblLimsMenuTop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLimsMenuTop.setForeground(new java.awt.Color(67, 72, 79));
        lblLimsMenuTop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLimsMenuTop.setText("L  MS");
        pnlTopMenu.add(lblLimsMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_chemistry_lab_32.png"))); // NOI18N
        jLabel15.setText("Reagentes");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnlTopMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogOut)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(lblLogOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTopMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlDocumentos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDocumentosMouseExited(evt);
            }
        });
        pnlDocumentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_attach_32.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Digitalizados");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Documentos");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDocumentos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 6, 110, -1));

        lblLaboratorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLaboratorio.setText("Reagentes");

        pnlReagente.setBackground(new java.awt.Color(255, 255, 255));
        pnlReagente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReagenteMouseExited(evt);
            }
        });
        pnlReagente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_solucao_32.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Reagentes");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReagente.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, -1));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLaboratorio)
                            .addComponent(pnlReagente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 639, Short.MAX_VALUE))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaboratorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReagente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseReleased
        logout();
    }//GEN-LAST:event_lblLogOutMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        trocarSenha();
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        dadosUsuario();
    }//GEN-LAST:event_jLabel5MouseReleased

    private void pnlDocumentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseExited
        MouseEventButton.setMouseExited(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseExited

    private void pnlDocumentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseEntered
        MouseEventButton.setMouseEntered(pnlDocumentos);
    }//GEN-LAST:event_pnlDocumentosMouseEntered

    private void pnlDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocumentosMouseClicked
        Frames.carregarJFrame(FrmDocumentos.class);
    }//GEN-LAST:event_pnlDocumentosMouseClicked

    private void pnlReagenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseClicked
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Frames.carregarJFrame(FrmReagente.class);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pnlReagenteMouseClicked

    private void pnlReagenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseEntered
        MouseEventButton.setMouseEntered(pnlReagente);
    }//GEN-LAST:event_pnlReagenteMouseEntered

    private void pnlReagenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReagenteMouseExited
        MouseEventButton.setMouseExited(pnlReagente);
    }//GEN-LAST:event_pnlReagenteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    private void carregar() {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setIconImage(new Frames().getIcon());
        setTitle("Controle de Qualidade - Modulo CQ_Desktop - Usuário: " + System.getProperty("user"));

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                logout();
            }
        });
    }

    private void logout() {
        int option = JOptionPane.showConfirmDialog(
                null,
                "Tem certeza de que deseja fechar o aplicativo?",
                "Confirmação de Fechamento",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            LoginDAO loginDAO = new LoginDAO();
            UsuarioDAO userDAO = new UsuarioDAO();
            try {
                Usuario user = new UsuarioDAO().findById(Usuario.class,
                        Long.parseLong(System.getProperty("user_id")));
                loginDAO.logoffUsuario(user);
                userDAO.atualizarLogoffUsuario(user);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao Gravar Logout" + ex);
            }
            System.exit(0);
        }
    }

    private void checkTempoInatividade() {
        Long eventMask = AWTEvent.KEY_EVENT_MASK | AWTEvent.MOUSE_EVENT_MASK;
        Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
            @Override
            public void eventDispatched(AWTEvent e) {
                timer = System.currentTimeMillis();
            }
        }, eventMask);
        timer = System.currentTimeMillis();
        new Thread(new Runnable() {
            @Override
            public void run() {
                Integer tempo;
                try {
                    tempo = new SegurancaDAO().findByTipo(Seguranca.FECHAR).getNumero();
                } catch (Exception ex) {
                    tempo = 120;
                }
                while (true) {
                    if (System.currentTimeMillis() - timer > tempo * 60000) {
                        System.exit(0);
                        break;
                    }
                }
            }
        }).start();
    }

    private void trocarSenha() {
        try {
            FrmSenhaAlterar frm = new FrmSenhaAlterar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar Senha" + ex);
        }
    }

    private void dadosUsuario() {
        try {
            FrmUsuarioVisualizar frm = new FrmUsuarioVisualizar(null, true);
            frm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Abrir" + ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLabMenuTop;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblLimsMenuTop;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblLogoMenuTop;
    private javax.swing.JPanel pnlDocumentos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlReagente;
    private javax.swing.JPanel pnlTopMenu;
    // End of variables declaration//GEN-END:variables
}
